### ISSUE TITLE
Add support for TYPO3 7.6

### ISSUE THREAD

**Issue by digedag** [digedag/rn_base#34]
Mit Veröffentlichung der neuen LTS Version sollte auch rn_base entsprechend erweitert werden. Support für 4.5 soll dabei erhalten bleiben.

**TODOs für Plugins**

**TODOs im Backend**
- [x] Support für neue Wizard-Integration
- [x] Support von Modulen mit DISPATCH-Modus
- [x] Rendering für Icon-Buttons (t3lib_iconWorks)
- [x] Rendern von TCA-Feldern (getSoloField())
- [x] Rendern von freien Datumsfeldern `Tx_Rnbase_Backend_Form_ToolBox::createDateInput()`
- [x] Formatierung Tabs-Menu
- [x] systemkonformes Modul-Rendering (neue Basisklasse, Support für TYPO3\CMS\Backend\Template\ModuleTemplate)

**Comment by digedag** [comment]
Ich habe gerade festgestellt, daß wir im BE ein größeres Problem haben. Die API für die Formular-Erzeugung wurde komplett umgestellt. Die ehemalige FormEngine gibt es nicht mehr. Und eine neue, zentrale Formular-Klasse habe ich noch nicht gefunden. Ich habe aber auch noch nicht weiter gesucht.
Aktuell scheitert das Rendering der BE-Module damit bei der Initialisierung des FormTools... :anguished:

**Comment by hannesbochmann** [comment]
Ich könnte mir gut vorstellen dass das alles auf fluid umgestellt wurde und dort mit Viewhelpern alle Formularelemente erzeugt werden. Das wäre für uns natürlich der Worst Case. Dann würde uns wahrscheinlich nichts übrig bleiben als einen Backport der FormEngine zu machen.

**Comment by hannesbochmann** [comment]
Brauchen wir das eigentlich überhaupt an so vielen Stellen?

**Comment by digedag** [comment]
Nein das funktioniert ohne Fluid. Wir benutzen bisher for allem die Methode getSoloField() um einzelne Formularfelder zu erzeugen. In der 7.6 gibt es jetzt für die Formulare eine NodeFactory, die diese Aufgabe übernommen hat. Sie stellt aber leider keine analoge Methode bereit, sondern rendert das gesamte Formular. Am Ende liefert sie aber auch den HTML-Code, den wir benötigen.
Mit einer Proxy-Klasse läßt sich da sicher was machen.

**Comment by digedag** [comment]
Ich habe gerade ein erstes Hidden-Field testweise rausgerendert. Es kam zwar ohne Label aber kam eine Checkbox! :smile:

**Comment by digedag** [comment]
Ich möchte mal die Frage in den Raum werfen, ob wir bei den Backend-Modulen die Basisklasse von TYPO3 (t3lib_SCbase bzw. \TYPO3\CMS\Backend\Module\BaseScriptClass) überhaupt noch benötigen. Meiner Ansicht nach ist so ziemlich der gesamte relevante Code inzwischen mit Erweiterungen in unserer eigenen Basisklasse gelandet. Wenn wir den restlichen Code noch nachziehen, der wirklich notwendig ist, wird vermutlich auch der Ablauf etwas klarer.

Des weiteren gibt es in der 7.6 jetzt die Klasse ModuleTemplate. Diese stellt den gesamten HTML-Rahmen für ein Modul bereit. Mit folgendem Code-Schnipsel kann man ein optisch passendes Modul für die 7.6 mit Funktions-Menü und Breadcrumb rausrendern:
```php
$doc = tx_rnbase::makeInstance(TYPO3\CMS\Backend\Template\DocumentTemplate::class);
/* @var $moduleTemplate TYPO3\CMS\Backend\Template\ModuleTemplate */
$moduleTemplate = tx_rnbase::makeInstance(TYPO3\CMS\Backend\Template\ModuleTemplate::class);
$moduleTemplate->getPageRenderer()->loadJquery();
$moduleTemplate->getDocHeaderComponent()->setMetaInformation($this->pageinfo);
$moduleTemplate->registerModuleMenu($this->getName());
$content = $moduleTemplate->header('Ein Header');
$content .= $moduleTemplate->section('Ein Abschnitt');
$moduleTemplate->setContent($content);
$content = $moduleTemplate->renderContent();
```
Das ganze ist leider noch etwas unausgegoren. Damit das CSS geladen wird, muss man eine Instanz von DocumentTemplate erzeugen. In deren Konstruktor wird das CSS für's Backend integriert. Einen sauberen Weg wird es dafür vermutlich erst in der nächste Version gegeben. Wir sollten das also auf jeden Fall flexibel halten. :wink: 

Davon abgesehen könnte der Modul-Content wie bisher erzeugt. Er wird dann aber nicht mehr über die Marker integriert, sondern einfach als $content in der ModuleTemplate-Instanz gesetzt. Für die alten Versionen belassen wir es beim bisherigen Weg.

**Comment by oliverklee** [comment]
Are there any remaining issues for 7.6 compatibility?

**Comment by digedag** [comment]
Today I activated new layout for 7.6 and higher. Once this is successfully tested in some extensions, we can close this ticket.
